//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KTPMUDMVVM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoSoChanNuoi
    {
        public string MaCN { get; set; }
        public string Ten { get; set; }
        public string MaDV { get; set; }
        public Nullable<int> SoLuongDV { get; set; }
        public string SoDT { get; set; }
        public string MaXa { get; set; }
        public string MaTCCN { get; set; }
        public string MaDK { get; set; }
        public string MaDB { get; set; }
        public string MaGCN { get; set; }
        public string MaLCS { get; set; }
    
        public virtual GiayChungNhan GiayChungNhan { get; set; }
        public virtual LoaiCoSo LoaiCoSo { get; set; }
        public virtual ToChucCaNhan ToChucCaNhan { get; set; }
        public virtual Dichbenh Dichbenh { get; set; }
        public virtual DieuKienChanNuoi DieuKienChanNuoi { get; set; }
        public virtual DongVat DongVat { get; set; }
        public virtual Xa Xa { get; set; }
    }
}
