//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KTPMUDMVVM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhuTamGiu
    {
        public string MaKhu { get; set; }
        public string TenKhu { get; set; }
        public string MaDV { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public string MaXa { get; set; }
        public Nullable<System.DateTime> NgayTG { get; set; }
    
        public virtual DongVat DongVat { get; set; }
        public virtual Xa Xa { get; set; }
    }
}
