//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KTPMUDMVVM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nguoi_dung
    {
        public string MaND { get; set; }
        public string TenDN { get; set; }
        public string MatKhau { get; set; }
        public string Chuc_vu { get; set; }
        public string TenHienThi { get; set; }
        public string MaXa { get; set; }
    
        public virtual Xa Xa { get; set; }
    }
}
