//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KTPMUDMVVM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPhamXuLyChatThai
    {
        public string MaSP { get; set; }
        public string TenSP { get; set; }
        public string LoaiSP { get; set; }
        public Nullable<System.DateTime> HanSD { get; set; }
        public string MaSX { get; set; }
        public string MaKN { get; set; }
    
        public virtual CoSoKhaoNghiemSP CoSoKhaoNghiemSP { get; set; }
        public virtual CoSoSanXuatSP CoSoSanXuatSP { get; set; }
    }
}
