//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KTPMUDMVVM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongKeChanNuoi
    {
        public string MaTK { get; set; }
        public Nullable<int> SoLuongCNNL { get; set; }
        public Nullable<System.DateTime> NgayTK { get; set; }
    }
}
