//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KTPMUDMVVM.ViewModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Thuoc
    {
        public string MaT { get; set; }
        public string TenT { get; set; }
        public string MaDV { get; set; }
        public Nullable<System.DateTime> NgaySX { get; set; }
        public Nullable<System.DateTime> HanSD { get; set; }
    
        public virtual DongVat DongVat { get; set; }
    }
}
